# lib/dynamic_supervisor_example/worker_supervisor.ex
defmodule GameOfLife.Universe.Template do
  alias GameOfLife.Universe.Dimensions
  alias GameOfLife.Cell.Position

  def dimensions("random"), do: %Dimensions{width: 100, height: 100}
  def dimensions("beacon"), do: %Dimensions{width: 6, height: 6}
  def dimensions("pulsar"), do: %Dimensions{width: 17, height: 17}
  def dimensions("rocket"), do: %Dimensions{width: 21, height: 21}
  def dimensions("penta_decathlon"), do: %Dimensions{width: 11, height: 18}

  def names do
    ["random", "beacon", "pulsar", "penta_decathlon", "rocket"]
  end

  def initial_state("beacon") do
    [
      %Position{x: 1, y: 1},
      %Position{x: 1, y: 2},
      %Position{x: 2, y: 1},
      %Position{x: 3, y: 4},
      %Position{x: 4, y: 3},
      %Position{x: 4, y: 4}
    ]
  end

  def initial_state("pulsar") do
    [
      %Position{x: 4, y: 2},
      %Position{x: 5, y: 2},
      %Position{x: 6, y: 2},
      %Position{x: 10, y: 2},
      %Position{x: 11, y: 2},
      %Position{x: 12, y: 2},
      %Position{x: 2, y: 4},
      %Position{x: 7, y: 4},
      %Position{x: 9, y: 4},
      %Position{x: 14, y: 4},
      %Position{x: 2, y: 5},
      %Position{x: 7, y: 5},
      %Position{x: 9, y: 5},
      %Position{x: 14, y: 5},
      %Position{x: 2, y: 6},
      %Position{x: 7, y: 6},
      %Position{x: 9, y: 6},
      %Position{x: 14, y: 6},
      %Position{x: 4, y: 7},
      %Position{x: 5, y: 7},
      %Position{x: 6, y: 7},
      %Position{x: 10, y: 7},
      %Position{x: 11, y: 7},
      %Position{x: 12, y: 7},
      %Position{x: 4, y: 9},
      %Position{x: 5, y: 9},
      %Position{x: 6, y: 9},
      %Position{x: 10, y: 9},
      %Position{x: 11, y: 9},
      %Position{x: 12, y: 9},
      %Position{x: 2, y: 10},
      %Position{x: 7, y: 10},
      %Position{x: 9, y: 10},
      %Position{x: 14, y: 10},
      %Position{x: 2, y: 11},
      %Position{x: 7, y: 11},
      %Position{x: 9, y: 11},
      %Position{x: 14, y: 11},
      %Position{x: 2, y: 12},
      %Position{x: 7, y: 12},
      %Position{x: 9, y: 12},
      %Position{x: 14, y: 12},
      %Position{x: 4, y: 14},
      %Position{x: 5, y: 14},
      %Position{x: 6, y: 14},
      %Position{x: 10, y: 14},
      %Position{x: 11, y: 14},
      %Position{x: 12, y: 14}
    ]
  end

  def initial_state("penta_decathlon") do
    [
      %Position{x: 4, y: 5},
      %Position{x: 4, y: 6},
      %Position{x: 4, y: 7},
      %Position{x: 4, y: 8},
      %Position{x: 4, y: 9},
      %Position{x: 4, y: 10},
      %Position{x: 4, y: 11},
      %Position{x: 4, y: 12},
      %Position{x: 5, y: 5},
      %Position{x: 5, y: 7},
      %Position{x: 5, y: 8},
      %Position{x: 5, y: 9},
      %Position{x: 5, y: 10},
      %Position{x: 5, y: 12},
      %Position{x: 6, y: 5},
      %Position{x: 6, y: 6},
      %Position{x: 6, y: 7},
      %Position{x: 6, y: 8},
      %Position{x: 6, y: 9},
      %Position{x: 6, y: 10},
      %Position{x: 6, y: 11},
      %Position{x: 6, y: 12}
    ]
  end

  def initial_state("rocket") do
    [
      %Position{x: 10, y: 1},
      %Position{x: 9, y: 2},
      %Position{x: 10, y: 2},
      %Position{x: 11, y: 2},
      %Position{x: 8, y: 3},
      %Position{x: 9, y: 3},
      %Position{x: 10, y: 3},
      %Position{x: 11, y: 3},
      %Position{x: 12, y: 3},
      %Position{x: 7, y: 4},
      %Position{x: 8, y: 4},
      %Position{x: 9, y: 4},
      %Position{x: 11, y: 4},
      %Position{x: 12, y: 4},
      %Position{x: 13, y: 4},
      %Position{x: 6, y: 5},
      %Position{x: 7, y: 5},
      %Position{x: 8, y: 5},
      %Position{x: 12, y: 5},
      %Position{x: 13, y: 5},
      %Position{x: 14, y: 5},
      %Position{x: 5, y: 6},
      %Position{x: 6, y: 6},
      %Position{x: 7, y: 6},
      %Position{x: 8, y: 6},
      %Position{x: 12, y: 6},
      %Position{x: 13, y: 6},
      %Position{x: 14, y: 6},
      %Position{x: 15, y: 6},
      %Position{x: 5, y: 7},
      %Position{x: 6, y: 7},
      %Position{x: 7, y: 7},
      %Position{x: 8, y: 7},
      %Position{x: 9, y: 7},
      %Position{x: 11, y: 7},
      %Position{x: 12, y: 7},
      %Position{x: 13, y: 7},
      %Position{x: 14, y: 7},
      %Position{x: 15, y: 7},
      %Position{x: 4, y: 8},
      %Position{x: 5, y: 8},
      %Position{x: 6, y: 8},
      %Position{x: 7, y: 8},
      %Position{x: 8, y: 8},
      %Position{x: 9, y: 8},
      %Position{x: 10, y: 8},
      %Position{x: 11, y: 8},
      %Position{x: 12, y: 8},
      %Position{x: 13, y: 8},
      %Position{x: 14, y: 8},
      %Position{x: 15, y: 8},
      %Position{x: 16, y: 8},
      %Position{x: 4, y: 9},
      %Position{x: 5, y: 9},
      %Position{x: 6, y: 9},
      %Position{x: 7, y: 9},
      %Position{x: 8, y: 9},
      %Position{x: 9, y: 9},
      %Position{x: 10, y: 9},
      %Position{x: 11, y: 9},
      %Position{x: 12, y: 9},
      %Position{x: 13, y: 9},
      %Position{x: 14, y: 9},
      %Position{x: 15, y: 9},
      %Position{x: 16, y: 9},
      %Position{x: 4, y: 10},
      %Position{x: 5, y: 10},
      %Position{x: 6, y: 10},
      %Position{x: 7, y: 10},
      %Position{x: 8, y: 10},
      %Position{x: 9, y: 10},
      %Position{x: 10, y: 10},
      %Position{x: 11, y: 10},
      %Position{x: 12, y: 10},
      %Position{x: 13, y: 10},
      %Position{x: 14, y: 10},
      %Position{x: 15, y: 10},
      %Position{x: 16, y: 10},
      %Position{x: 4, y: 11},
      %Position{x: 5, y: 11},
      %Position{x: 6, y: 11},
      %Position{x: 7, y: 11},
      %Position{x: 8, y: 11},
      %Position{x: 9, y: 11},
      %Position{x: 10, y: 11},
      %Position{x: 11, y: 11},
      %Position{x: 12, y: 11},
      %Position{x: 13, y: 11},
      %Position{x: 14, y: 11},
      %Position{x: 15, y: 11},
      %Position{x: 16, y: 11},
      %Position{x: 5, y: 12},
      %Position{x: 6, y: 12},
      %Position{x: 7, y: 12},
      %Position{x: 8, y: 12},
      %Position{x: 9, y: 12},
      %Position{x: 10, y: 12},
      %Position{x: 11, y: 12},
      %Position{x: 12, y: 12},
      %Position{x: 13, y: 12},
      %Position{x: 14, y: 12},
      %Position{x: 15, y: 12},
      %Position{x: 4, y: 13},
      %Position{x: 5, y: 13},
      %Position{x: 6, y: 13},
      %Position{x: 7, y: 13},
      %Position{x: 8, y: 13},
      %Position{x: 9, y: 13},
      %Position{x: 10, y: 13},
      %Position{x: 11, y: 13},
      %Position{x: 12, y: 13},
      %Position{x: 13, y: 13},
      %Position{x: 14, y: 13},
      %Position{x: 15, y: 13},
      %Position{x: 16, y: 13},
      %Position{x: 3, y: 14},
      %Position{x: 4, y: 14},
      %Position{x: 6, y: 14},
      %Position{x: 7, y: 14},
      %Position{x: 8, y: 14},
      %Position{x: 9, y: 14},
      %Position{x: 10, y: 14},
      %Position{x: 11, y: 14},
      %Position{x: 12, y: 14},
      %Position{x: 13, y: 14},
      %Position{x: 14, y: 14},
      %Position{x: 16, y: 14},
      %Position{x: 17, y: 14},
      %Position{x: 2, y: 15},
      %Position{x: 3, y: 15},
      %Position{x: 4, y: 15},
      %Position{x: 6, y: 15},
      %Position{x: 7, y: 15},
      %Position{x: 8, y: 15},
      %Position{x: 9, y: 15},
      %Position{x: 10, y: 15},
      %Position{x: 11, y: 15},
      %Position{x: 12, y: 15},
      %Position{x: 13, y: 15},
      %Position{x: 14, y: 15},
      %Position{x: 16, y: 15},
      %Position{x: 17, y: 15},
      %Position{x: 18, y: 15},
      %Position{x: 1, y: 16},
      %Position{x: 2, y: 16},
      %Position{x: 3, y: 16},
      %Position{x: 4, y: 16},
      %Position{x: 7, y: 16},
      %Position{x: 8, y: 16},
      %Position{x: 9, y: 16},
      %Position{x: 10, y: 16},
      %Position{x: 11, y: 16},
      %Position{x: 12, y: 16},
      %Position{x: 13, y: 16},
      %Position{x: 16, y: 16},
      %Position{x: 17, y: 16},
      %Position{x: 18, y: 16},
      %Position{x: 19, y: 16},
      %Position{x: 1, y: 17},
      %Position{x: 2, y: 17},
      %Position{x: 3, y: 17},
      %Position{x: 4, y: 17},
      %Position{x: 5, y: 17},
      %Position{x: 6, y: 17},
      %Position{x: 8, y: 17},
      %Position{x: 9, y: 17},
      %Position{x: 10, y: 17},
      %Position{x: 11, y: 17},
      %Position{x: 12, y: 17},
      %Position{x: 14, y: 17},
      %Position{x: 15, y: 17},
      %Position{x: 16, y: 17},
      %Position{x: 17, y: 17},
      %Position{x: 18, y: 17},
      %Position{x: 19, y: 17},
      %Position{x: 1, y: 18},
      %Position{x: 2, y: 18},
      %Position{x: 3, y: 18},
      %Position{x: 9, y: 18},
      %Position{x: 10, y: 18},
      %Position{x: 11, y: 18},
      %Position{x: 17, y: 18},
      %Position{x: 18, y: 18},
      %Position{x: 19, y: 18},
      %Position{x: 10, y: 19},
    ]
  end
end
